name: mem-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - librosa
  - zipfile
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pandas
  - numpy
  - pathlib
  - lyricsgenius
  - zipfile
  - urllib.request
  - shutil
  - tqdm
  - librosa.display
  - matplotlib.pyplot
  - scipy
  - scikit-learn.metrics
  - pip:
      - transformers
