name: mem-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - librosa
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - scikit-learn
  - ffmpeg            # necesario para librosa y .mp3
  - jupyterlab
  - ipykernel

  - pip:
      - lyricsgenius == 
      - python-dotenv
      - transformers
