name: mem-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - librosa
  - zipfile
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - pandas
  - numpy
  - pip:
      - transformers
