name: mem-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11                 # ACTUALIZADO: Resuelve el error de 'Self' typing
  - pip
  - numpy
  - pandas
  - librosa
  - scipy
  - matplotlib
  - seaborn
  - tqdm
  - scikit-learn
  - ffmpeg                      # Crucial para yt-dlp y librosa
  - jupyterlab
  - ipykernel

  - pip:
      - python-dotenv
      - transformers            # Para cuando lleguemos al modelado de texto
      - lyricsgenius            # Versi√≥n moderna compatible con Py3.11
      - spotipy                 # Para ExtractDataV2 (Paso 1)
      - langdetect              # Para ExtractDataV2 (Paso 2)
      - yt-dlp                  # Para ExtractDataV2 (Paso 3)